# Generated by Django 4.0.6 on 2022-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
